package jidnet.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Hashtable;
import java.util.Map.Entry;
import java.util.Properties;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import jidnet.idnet.Helper;
import jidnet.idnet.Idiotype;
import jidnet.idnet.DeterminantBits;

/**
 *
 * @author Sven Willner
 */
public class MainWindow extends javax.swing.JFrame {

    private Timer timer;
    private int redrawDelay;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();

        updateParamSpinners();

        spinnerMax_s.setValue(Application.getIdnetManager().getmax_s());
        redrawDelay = Integer.parseInt(Application.getConfiguration().getProperty("redraw_delay", "10"));
        spinnerRedrawDelay.setValue(redrawDelay);

        for (Properties p : Application.getConfigurations())
            ((DefaultListModel) configurationsList.getModel()).addElement(p.getProperty("name"));

        this.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);

        timer = new Timer(10, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                for (int i = 0; i < redrawDelay; i++) {
                    Application.getIdnetManager().iterate();
                    afterIteration();
                }
                updateIdnetStatistics();
            }

        });

    }

    ;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawTypeButtonGroup = new javax.swing.ButtonGroup();
        topologyDrawTypeButtonGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        runButton = new javax.swing.JToggleButton();
        resetButton = new javax.swing.JButton();
        recalcButton = new javax.swing.JButton();
        stepButton = new javax.swing.JButton();
        Step10000Button = new javax.swing.JButton();
        spinnerSeed = new javax.swing.JSpinner();
        reseedButton = new javax.swing.JButton();
        reseedAndResetButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        saveNetworkButton = new javax.swing.JButton();
        loadNetworkButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        cogDiagramPanel = new COGDiagramPanel(Application.getIdnetManager());
        network1DPanel = new jidnet.gui.Network1DPanel(Application.getIdnetManager());
        network2DPanel = new Network2DPanel(Application.getIdnetManager());
        arrangebyDetBitsButton = new javax.swing.JButton();
        defArragementButton = new javax.swing.JButton();
        calcGroupOccButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupOccText = new javax.swing.JTextArea();
        drawCurrentRadioButton = new javax.swing.JRadioButton();
        drawMeanOccsRadioButton = new javax.swing.JRadioButton();
        buttonArangeByCustomBits = new javax.swing.JButton();
        linkWeightingPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spinnerLinkW0 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        spinnerLinkW1 = new javax.swing.JSpinner();
        spinnerLinkW2 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        spinnerLinkW3 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spinnerLinkW4 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        spinnerLinkW5 = new javax.swing.JSpinner();
        spinnerLinkW6 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        spinnerLinkW7 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spinnerLinkW8 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        spinnerLinkW9 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        spinnerLinkW11 = new javax.swing.JSpinner();
        spinnerLinkW10 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        spinnerp_deadly = new javax.swing.JSpinner();
        setp_deadlyButton = new javax.swing.JButton();
        clusterPanel = new javax.swing.JPanel();
        calcClustersButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clustersText = new javax.swing.JTextArea();
        networkTopologyPanel = new NetworkTopologyPanel(Application.getIdnetManager());
        buttonTopologyDrawCustomBitGroups = new javax.swing.JButton();
        topologyDrawMeansRadioButton = new javax.swing.JRadioButton();
        topologyDrawCurrentRadioButton = new javax.swing.JRadioButton();
        configurationsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        configurationsList = new javax.swing.JList();
        newConfigButton = new javax.swing.JButton();
        loadConfigButton = new javax.swing.JButton();
        removeConfigButton = new javax.swing.JButton();
        overwriteConfigButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        spinnerRedrawDelay = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerp = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinnert_l = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinnert_u = new javax.swing.JSpinner();
        spinnerMax_s = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        totalOccLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerN = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        checkExtStat = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        textCustomBitMask = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        textCustomBitValues = new javax.swing.JTextField();
        buttonAutoDetBits = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jSplitPane1.setDividerLocation(175);

        runButton.setText("Run");
        runButton.setName("runButton"); // NOI18N
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.setName("resetButton"); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        recalcButton.setText("Recalc");
        recalcButton.setName("recalcButton"); // NOI18N
        recalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recalcButtonActionPerformed(evt);
            }
        });

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        Step10000Button.setText("Step 10000");
        Step10000Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step10000ButtonActionPerformed(evt);
            }
        });

        spinnerSeed.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), null, null, Long.valueOf(1L)));
        spinnerSeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSeedStateChanged(evt);
            }
        });

        reseedButton.setText("Reseed");
        reseedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reseedButtonActionPerformed(evt);
            }
        });

        reseedAndResetButton.setText("Reseed & Reset");
        reseedAndResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reseedAndResetButtonActionPerformed(evt);
            }
        });

        saveNetworkButton.setText("Save network");
        saveNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetworkButtonActionPerformed(evt);
            }
        });

        loadNetworkButton.setText("Load network");
        loadNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNetworkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(runButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(stepButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(Step10000Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(reseedAndResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(recalcButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(spinnerSeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(reseedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(saveNetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(loadNetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Step10000Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reseedAndResetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recalcButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spinnerSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reseedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(loadNetworkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNetworkButton)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel3);

        cogDiagramPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cogDiagramPanelLayout = new javax.swing.GroupLayout(cogDiagramPanel);
        cogDiagramPanel.setLayout(cogDiagramPanelLayout);
        cogDiagramPanelLayout.setHorizontalGroup(
            cogDiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        cogDiagramPanelLayout.setVerticalGroup(
            cogDiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Center of gravity", cogDiagramPanel);

        network1DPanel.setBackground(new java.awt.Color(255, 255, 255));
        network1DPanel.setName("network1DPanel"); // NOI18N

        javax.swing.GroupLayout network1DPanelLayout = new javax.swing.GroupLayout(network1DPanel);
        network1DPanel.setLayout(network1DPanelLayout);
        network1DPanelLayout.setHorizontalGroup(
            network1DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        network1DPanelLayout.setVerticalGroup(
            network1DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("1D View", network1DPanel);

        network2DPanel.setBackground(new java.awt.Color(255, 255, 255));

        arrangebyDetBitsButton.setText("Arrange by det. bit groups");
        arrangebyDetBitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrangebyDetBitsButtonActionPerformed(evt);
            }
        });

        defArragementButton.setText("Default arrangement");
        defArragementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defArragementButtonActionPerformed(evt);
            }
        });

        calcGroupOccButton.setText("Calculate group occupations");
        calcGroupOccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcGroupOccButtonActionPerformed(evt);
            }
        });

        groupOccText.setEditable(false);
        jScrollPane3.setViewportView(groupOccText);

        drawTypeButtonGroup.add(drawCurrentRadioButton);
        drawCurrentRadioButton.setSelected(true);
        drawCurrentRadioButton.setText("Draw current network");
        drawCurrentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRadioButtonActionPerformed(evt);
            }
        });

        drawTypeButtonGroup.add(drawMeanOccsRadioButton);
        drawMeanOccsRadioButton.setText("Draw mean occupations");
        drawMeanOccsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRadioButtonActionPerformed(evt);
            }
        });

        buttonArangeByCustomBits.setText("Arrange by custom bits");
        buttonArangeByCustomBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonArangeByCustomBitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout network2DPanelLayout = new javax.swing.GroupLayout(network2DPanel);
        network2DPanel.setLayout(network2DPanelLayout);
        network2DPanelLayout.setHorizontalGroup(
            network2DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, network2DPanelLayout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addGroup(network2DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonArangeByCustomBits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawMeanOccsRadioButton)
                    .addComponent(drawCurrentRadioButton)
                    .addComponent(calcGroupOccButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(defArragementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arrangebyDetBitsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        network2DPanelLayout.setVerticalGroup(
            network2DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(network2DPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arrangebyDetBitsButton)
                .addGap(18, 18, 18)
                .addComponent(defArragementButton)
                .addGap(18, 18, 18)
                .addComponent(calcGroupOccButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(drawCurrentRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawMeanOccsRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonArangeByCustomBits)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2D View", network2DPanel);

        jLabel9.setText("Missmatches");

        jLabel10.setText("Link weighting");

        jLabel11.setText("0");

        spinnerLinkW0.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setText("1");

        spinnerLinkW1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        spinnerLinkW2.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel13.setText("2");

        spinnerLinkW3.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel14.setText("3");

        jLabel15.setText("4");

        spinnerLinkW4.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel16.setText("5");

        spinnerLinkW5.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        spinnerLinkW6.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel17.setText("6");

        spinnerLinkW7.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel18.setText("7");

        spinnerLinkW8.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel19.setText("8");

        spinnerLinkW9.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel20.setText("9");

        spinnerLinkW11.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        spinnerLinkW10.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        spinnerLinkW10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLinkWeightingChanged(evt);
            }
        });

        jLabel21.setText("10");

        jLabel22.setText("11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerLinkW11, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW10, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(spinnerLinkW9, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerLinkW11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addContainerGap())
        );

        jLabel23.setText("Propability of mismatch being deadly:");

        spinnerp_deadly.setModel(new javax.swing.SpinnerNumberModel(0.3d, 0.0d, 1.0d, 0.1d));

        setp_deadlyButton.setText("Set");
        setp_deadlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setp_deadlyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linkWeightingPanelLayout = new javax.swing.GroupLayout(linkWeightingPanel);
        linkWeightingPanel.setLayout(linkWeightingPanelLayout);
        linkWeightingPanelLayout.setHorizontalGroup(
            linkWeightingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkWeightingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linkWeightingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(linkWeightingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerp_deadly, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setp_deadlyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        linkWeightingPanelLayout.setVerticalGroup(
            linkWeightingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkWeightingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(linkWeightingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spinnerp_deadly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setp_deadlyButton))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Link weighting", linkWeightingPanel);

        calcClustersButton.setText("Calc clusters");
        calcClustersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcClustersButtonActionPerformed(evt);
            }
        });

        clustersText.setEditable(false);
        jScrollPane2.setViewportView(clustersText);

        javax.swing.GroupLayout clusterPanelLayout = new javax.swing.GroupLayout(clusterPanel);
        clusterPanel.setLayout(clusterPanelLayout);
        clusterPanelLayout.setHorizontalGroup(
            clusterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clusterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(calcClustersButton))
                .addContainerGap())
        );
        clusterPanelLayout.setVerticalGroup(
            clusterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcClustersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clusters", clusterPanel);

        networkTopologyPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonTopologyDrawCustomBitGroups.setText("Draw custom det. bits groups");
        buttonTopologyDrawCustomBitGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTopologyDrawCustomBitGroupsActionPerformed(evt);
            }
        });

        topologyDrawTypeButtonGroup.add(topologyDrawMeansRadioButton);
        topologyDrawMeansRadioButton.setText("Draw means");
        topologyDrawMeansRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topologyDrawTypeRadioButtonActionPerformed(evt);
            }
        });

        topologyDrawTypeButtonGroup.add(topologyDrawCurrentRadioButton);
        topologyDrawCurrentRadioButton.setSelected(true);
        topologyDrawCurrentRadioButton.setText("Draw current topology");
        topologyDrawCurrentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topologyDrawTypeRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout networkTopologyPanelLayout = new javax.swing.GroupLayout(networkTopologyPanel);
        networkTopologyPanel.setLayout(networkTopologyPanelLayout);
        networkTopologyPanelLayout.setHorizontalGroup(
            networkTopologyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, networkTopologyPanelLayout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addGroup(networkTopologyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topologyDrawMeansRadioButton)
                    .addComponent(topologyDrawCurrentRadioButton)
                    .addComponent(buttonTopologyDrawCustomBitGroups))
                .addContainerGap())
        );
        networkTopologyPanelLayout.setVerticalGroup(
            networkTopologyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkTopologyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTopologyDrawCustomBitGroups)
                .addGap(18, 18, 18)
                .addComponent(topologyDrawCurrentRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topologyDrawMeansRadioButton)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Topology", networkTopologyPanel);

        configurationsList.setModel(new DefaultListModel());
        configurationsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(configurationsList);

        newConfigButton.setText("New configuration");
        newConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConfigButtonActionPerformed(evt);
            }
        });

        loadConfigButton.setText("Load selected");
        loadConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadConfigButtonActionPerformed(evt);
            }
        });

        removeConfigButton.setText("Remove selected");
        removeConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConfigButtonActionPerformed(evt);
            }
        });

        overwriteConfigButton.setText("Overwrite selected");
        overwriteConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overwriteConfigButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configurationsPanelLayout = new javax.swing.GroupLayout(configurationsPanel);
        configurationsPanel.setLayout(configurationsPanelLayout);
        configurationsPanelLayout.setHorizontalGroup(
            configurationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configurationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overwriteConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        configurationsPanelLayout.setVerticalGroup(
            configurationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configurationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configurationsPanelLayout.createSequentialGroup()
                        .addComponent(newConfigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadConfigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(overwriteConfigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeConfigButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(403, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configurations", configurationsPanel);

        jPanel5.setPreferredSize(new java.awt.Dimension(681, 163));

        spinnerRedrawDelay.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerRedrawDelay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRedrawDelayStateChanged(evt);
            }
        });

        jLabel1.setText("Redraw Delay");

        jLabel2.setText("t =");

        tLabel.setText("0");

        jLabel3.setText("p =");

        spinnerp.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.0010d));
        spinnerp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerpStateChanged(evt);
            }
        });

        jLabel4.setText("t_l =");

        spinnert_l.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        spinnert_l.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnert_lStateChanged(evt);
            }
        });

        jLabel5.setText("t_u =");

        spinnert_u.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        spinnert_u.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnert_uStateChanged(evt);
            }
        });

        spinnerMax_s.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.01d)));
        spinnerMax_s.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerMax_sStateChanged(evt);
            }
        });

        jLabel6.setText("max_s =");

        totalOccLabel.setText("0");

        jLabel8.setText("total occ =");

        spinnerN.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerNStateChanged(evt);
            }
        });

        jLabel7.setText("N =");

        checkExtStat.setText("Extended statistics");
        checkExtStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkExtStatActionPerformed(evt);
            }
        });

        jLabel24.setText("mask = ");

        jLabel25.setText("values =");

        buttonAutoDetBits.setText("Auto det. bits");
        buttonAutoDetBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAutoDetBitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkExtStat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalOccLabel)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnerp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnert_l, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnert_u, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnerN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnerMax_s, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnerRedrawDelay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCustomBitValues, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(textCustomBitMask, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAutoDetBits, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerRedrawDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnert_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnert_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerMax_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalOccLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(buttonAutoDetBits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(textCustomBitMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCustomBitValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkExtStat)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateParamSpinners() {
        spinnerp.setValue(Application.getIdnetManager().getp());
        spinnert_l.setValue(Application.getIdnetManager().gett_l());
        spinnert_u.setValue(Application.getIdnetManager().gett_u());
        spinnerN.setValue(Application.getIdnetManager().getN());
        spinnerSeed.setValue(Application.getIdnetManager().getSeed());

        spinnerLinkW0.setValue(Application.getIdnetManager().getLinkWeighting(0));
        spinnerLinkW1.setValue(Application.getIdnetManager().getLinkWeighting(1));
        spinnerLinkW2.setValue(Application.getIdnetManager().getLinkWeighting(2));
        spinnerLinkW3.setValue(Application.getIdnetManager().getLinkWeighting(3));
        spinnerLinkW4.setValue(Application.getIdnetManager().getLinkWeighting(4));
        spinnerLinkW5.setValue(Application.getIdnetManager().getLinkWeighting(5));
        spinnerLinkW6.setValue(Application.getIdnetManager().getLinkWeighting(6));
        spinnerLinkW7.setValue(Application.getIdnetManager().getLinkWeighting(7));
        spinnerLinkW8.setValue(Application.getIdnetManager().getLinkWeighting(8));
        spinnerLinkW9.setValue(Application.getIdnetManager().getLinkWeighting(9));
        spinnerLinkW10.setValue(Application.getIdnetManager().getLinkWeighting(10));
        spinnerLinkW11.setValue(Application.getIdnetManager().getLinkWeighting(11));
    }

    public void updateIdnetStatistics() {
        tLabel.setText(Integer.toString(Application.getIdnetManager().gett()));
        totalOccLabel.setText(Integer.toString(Application.getIdnetManager().gettotal_sum_n()));
        repaint();
    }

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if (timer.isRunning())
            timer.stop();
        else
            timer.start();
    }//GEN-LAST:event_runButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        Application.getIdnetManager().reseed((Long) spinnerSeed.getValue());
        Application.getIdnetManager().reset();
        ((NetworkTopologyPanel) networkTopologyPanel).recalc();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void recalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recalcButtonActionPerformed
        Application.getIdnetManager().recalc();
        ((NetworkTopologyPanel) networkTopologyPanel).recalc();
    }//GEN-LAST:event_recalcButtonActionPerformed

    private void spinnerRedrawDelayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRedrawDelayStateChanged
        redrawDelay = ((Integer) spinnerRedrawDelay.getValue()).intValue();
        Application.getConfiguration().setProperty("redraw_delay", ((Integer) spinnerRedrawDelay.getValue()).toString());
    }//GEN-LAST:event_spinnerRedrawDelayStateChanged

    private void spinnerpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerpStateChanged
        Application.getIdnetManager().setp((Double) spinnerp.getValue());
    }//GEN-LAST:event_spinnerpStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Application.closing();
    }//GEN-LAST:event_formWindowClosing

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        Application.getIdnetManager().iterate();
        afterIteration();
        updateIdnetStatistics();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void arrangebyDetBitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrangebyDetBitsButtonActionPerformed
        ((Network2DPanel) network2DPanel).arrangeByDetBitGroups();
    }//GEN-LAST:event_arrangebyDetBitsButtonActionPerformed

    private void spinnerMax_sStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerMax_sStateChanged
        Application.getIdnetManager().setmax_s((Double) spinnerMax_s.getValue());
    }//GEN-LAST:event_spinnerMax_sStateChanged

    private void Step10000ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step10000ButtonActionPerformed
        Application.getIdnetManager().iterate(10000);
    }//GEN-LAST:event_Step10000ButtonActionPerformed

    private void spinnerNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerNStateChanged
        Application.getIdnetManager().setN((Integer) spinnerN.getValue());
    }//GEN-LAST:event_spinnerNStateChanged

    private void defArragementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defArragementButtonActionPerformed
        ((Network2DPanel) network2DPanel).arrangeDefault();
    }//GEN-LAST:event_defArragementButtonActionPerformed

    private void spinnerLinkWeightingChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerLinkWeightingChanged
        if (evt.getSource().equals(spinnerLinkW0))
            Application.getIdnetManager().setLinkWeighting(0, (Double) spinnerLinkW0.getValue());
        else if (evt.getSource().equals(spinnerLinkW1))
            Application.getIdnetManager().setLinkWeighting(1, (Double) spinnerLinkW1.getValue());
        else if (evt.getSource().equals(spinnerLinkW2))
            Application.getIdnetManager().setLinkWeighting(2, (Double) spinnerLinkW2.getValue());
        else if (evt.getSource().equals(spinnerLinkW3))
            Application.getIdnetManager().setLinkWeighting(3, (Double) spinnerLinkW3.getValue());
        else if (evt.getSource().equals(spinnerLinkW4))
            Application.getIdnetManager().setLinkWeighting(4, (Double) spinnerLinkW4.getValue());
        else if (evt.getSource().equals(spinnerLinkW5))
            Application.getIdnetManager().setLinkWeighting(5, (Double) spinnerLinkW5.getValue());
        else if (evt.getSource().equals(spinnerLinkW6))
            Application.getIdnetManager().setLinkWeighting(6, (Double) spinnerLinkW6.getValue());
        else if (evt.getSource().equals(spinnerLinkW7))
            Application.getIdnetManager().setLinkWeighting(7, (Double) spinnerLinkW7.getValue());
        else if (evt.getSource().equals(spinnerLinkW8))
            Application.getIdnetManager().setLinkWeighting(8, (Double) spinnerLinkW8.getValue());
        else if (evt.getSource().equals(spinnerLinkW9))
            Application.getIdnetManager().setLinkWeighting(9, (Double) spinnerLinkW9.getValue());
        else if (evt.getSource().equals(spinnerLinkW10))
            Application.getIdnetManager().setLinkWeighting(10, (Double) spinnerLinkW10.getValue());
        else if (evt.getSource().equals(spinnerLinkW11))
            Application.getIdnetManager().setLinkWeighting(11, (Double) spinnerLinkW11.getValue());
        updateParamSpinners();
    }//GEN-LAST:event_spinnerLinkWeightingChanged

    private void spinnerSeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSeedStateChanged
        Application.getIdnetManager().reseed((Long) spinnerSeed.getValue());
    }//GEN-LAST:event_spinnerSeedStateChanged

    private void reseedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reseedButtonActionPerformed
        long seed = System.currentTimeMillis();
        spinnerSeed.setValue((Long) seed);
        Application.getIdnetManager().reseed(seed);
    }//GEN-LAST:event_reseedButtonActionPerformed

    private void setp_deadlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setp_deadlyButtonActionPerformed
        double[] lw = new double[12];
        double v = 1, p = (Double) spinnerp_deadly.getValue();
        for (int i = 0; i < 12; i++) {
            lw[i] = v;
            v *= (1 - p);
        }
        spinnerLinkW0.setValue(lw[0]);
        spinnerLinkW1.setValue(lw[1]);
        spinnerLinkW2.setValue(lw[2]);
        spinnerLinkW3.setValue(lw[3]);
        spinnerLinkW4.setValue(lw[4]);
        spinnerLinkW5.setValue(lw[5]);
        spinnerLinkW6.setValue(lw[6]);
        spinnerLinkW7.setValue(lw[7]);
        spinnerLinkW8.setValue(lw[8]);
        spinnerLinkW9.setValue(lw[9]);
        spinnerLinkW10.setValue(lw[10]);
        spinnerLinkW11.setValue(lw[11]);
    }//GEN-LAST:event_setp_deadlyButtonActionPerformed

    private void loadConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadConfigButtonActionPerformed
        int s = configurationsList.getSelectedIndex();
        if (s > -1) {
            Application.getIdnetManager().loadParams(Application.getConfigurations().get(s));
            Application.getIdnetManager().reset();
            updateParamSpinners();
        }
    }//GEN-LAST:event_loadConfigButtonActionPerformed

    private void reseedAndResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reseedAndResetButtonActionPerformed
        reseedButtonActionPerformed(evt);
        resetButtonActionPerformed(evt);
    }//GEN-LAST:event_reseedAndResetButtonActionPerformed

    private void newConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConfigButtonActionPerformed
        String name = JOptionPane.showInputDialog("Name:");
        if (name != null && !name.isEmpty()) {
            Properties p = new Properties();
            p.putAll(Application.getIdnetManager().getParams());
            p.setProperty("name", name);
            Application.getConfigurations().add(p);
            ((DefaultListModel) (configurationsList.getModel())).addElement(name);
        }
    }//GEN-LAST:event_newConfigButtonActionPerformed

    private void removeConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConfigButtonActionPerformed
        int s = configurationsList.getSelectedIndex();
        if (s > -1) {
            Application.getConfigurations().remove(s);
            ((DefaultListModel) configurationsList.getModel()).remove(s);
        }
    }//GEN-LAST:event_removeConfigButtonActionPerformed

    private void overwriteConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overwriteConfigButtonActionPerformed
        int s = configurationsList.getSelectedIndex();
        if (s > -1) {
            Properties p = new Properties();
            p.putAll(Application.getIdnetManager().getParams());
            p.setProperty("name", Application.getConfigurations().get(s).getProperty("name"));
            Application.getConfigurations().set(s, p);
        }
    }//GEN-LAST:event_overwriteConfigButtonActionPerformed

    private void spinnert_lStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnert_lStateChanged
        Application.getIdnetManager().sett_l((Double) spinnert_l.getValue());
    }//GEN-LAST:event_spinnert_lStateChanged

    private void spinnert_uStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnert_uStateChanged
        Application.getIdnetManager().sett_u((Double) spinnert_u.getValue());
    }//GEN-LAST:event_spinnert_uStateChanged

    private void saveNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetworkButtonActionPerformed
        String fileName = JOptionPane.showInputDialog("Filename:");
        if (fileName != null && !fileName.isEmpty())
            try {
                Application.getIdnetManager().saveNetwork(fileName);
            } catch (IOException io) {
                io.printStackTrace();
            }
    }//GEN-LAST:event_saveNetworkButtonActionPerformed

    private void loadNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNetworkButtonActionPerformed
        String fileName = JOptionPane.showInputDialog("Filename:");
        if (fileName != null && !fileName.isEmpty()) {
            try {
                Application.getIdnetManager().loadNetwork(fileName);
            } catch (IOException io) {
                io.printStackTrace();
                return;
            }
            JOptionPane.showMessageDialog(this, "Network snapshot loaded");
        }
    }//GEN-LAST:event_loadNetworkButtonActionPerformed

    private void calcClustersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcClustersButtonActionPerformed
        Vector<Vector<Idiotype>> clusters = Application.getIdnetManager().calcClusters();
        Hashtable<Integer, Integer> clusterSizes = new Hashtable<Integer, Integer>();
        for (Vector<Idiotype> cluster : clusters)
            if (clusterSizes.containsKey(cluster.size()))
                clusterSizes.put(cluster.size(), clusterSizes.get(cluster.size()) + 1);
            else
                clusterSizes.put(cluster.size(), 1);
        String text = "Clusters:\n\nSize\tNumber\n\n";
        for (Entry<Integer, Integer> e : clusterSizes.entrySet())
            text += e.getKey() + "\t" + e.getValue() + "\n";
        clustersText.setText(text);
    }//GEN-LAST:event_calcClustersButtonActionPerformed

    private void calcGroupOccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcGroupOccButtonActionPerformed
        String text = null;
        int d_m = Application.getIdnetManager().getd_m();
        if (drawCurrentRadioButton.isSelected()) {
            Application.getIdnetManager().calcDeterminantBits();
            text = "Group\tOcc.\n\n";
            for (int i = 0; i <= d_m; i++)
                text += "S_" + i + "\t" + Application.getIdnetManager().getGroupOccupation(i) + "\n";
        } else if (drawMeanOccsRadioButton.isSelected()) {
            text = "Group\tMean occ.\n\n";
            for (int i = 0; i <= d_m; i++)
                text += "S_" + i + "\t" + (double) ((int) (10000 * (double) Application.getIdnetManager().
                        getTotalGroupOccs()[i] / Application.getIdnetManager().gett() / Application.getIdnetManager().
                        calcGroupSize(i, d_m))) / 10000 + "\n";
        }
        groupOccText.setText(text);
    }//GEN-LAST:event_calcGroupOccButtonActionPerformed

    private void drawRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRadioButtonActionPerformed
        if (drawCurrentRadioButton.isSelected()) {
            Application.getIdnetManager().setCalcMeanGroupOccs(false);
            ((Network2DPanel) network2DPanel).setDrawType(Network2DPanel.DRAW_CURRENT);
        } else if (drawMeanOccsRadioButton.isSelected()) {
            Application.getIdnetManager().setCalcMeanGroupOccs(true);
            ((Network2DPanel) network2DPanel).setDrawType(Network2DPanel.DRAW_MEAN_OCCUPATIONS);
        }
    }//GEN-LAST:event_drawRadioButtonActionPerformed

    private void buttonArangeByCustomBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonArangeByCustomBitsActionPerformed
        DeterminantBits detBits = new DeterminantBits();
        detBits.mask = Integer.parseInt(textCustomBitMask.getText(), 2);
        detBits.values = Integer.parseInt(textCustomBitValues.getText(), 2);
        ((Network2DPanel) network2DPanel).arrangeByDetBitGroups(detBits);
    }//GEN-LAST:event_buttonArangeByCustomBitsActionPerformed

    private void checkExtStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkExtStatActionPerformed
        Application.getIdnetManager().setStatNeighbourOccupations(checkExtStat.isSelected());
    }//GEN-LAST:event_checkExtStatActionPerformed

    private void buttonAutoDetBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAutoDetBitsActionPerformed
        DeterminantBits detBits = Application.getIdnetManager().calcDeterminantBits();
        textCustomBitMask.setText(Helper.getBitString(detBits.mask));
        textCustomBitValues.setText(Helper.getBitString(detBits.values));
    }//GEN-LAST:event_buttonAutoDetBitsActionPerformed

    private void buttonTopologyDrawCustomBitGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTopologyDrawCustomBitGroupsActionPerformed
        DeterminantBits detBits = new DeterminantBits();
        detBits.mask = Integer.parseInt(textCustomBitMask.getText(), 2);
        detBits.values = Integer.parseInt(textCustomBitValues.getText(), 2);
        ((NetworkTopologyPanel) networkTopologyPanel).setDeterminantBits(detBits);
    }//GEN-LAST:event_buttonTopologyDrawCustomBitGroupsActionPerformed

    private void topologyDrawTypeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topologyDrawTypeRadioButtonActionPerformed
        if (topologyDrawCurrentRadioButton.isSelected())
            ((NetworkTopologyPanel) networkTopologyPanel).setDrawType(NetworkTopologyPanel.DRAW_CURRENT);
        else if (topologyDrawMeansRadioButton.isSelected())
            ((NetworkTopologyPanel) networkTopologyPanel).setDrawType(NetworkTopologyPanel.DRAW_TOTAL_MEANS);

    }//GEN-LAST:event_topologyDrawTypeRadioButtonActionPerformed

    public void afterIteration() {
        ((COGDiagramPanel) cogDiagramPanel).afterIteration();
        ((NetworkTopologyPanel) networkTopologyPanel).afterIteration();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Step10000Button;
    private javax.swing.JButton arrangebyDetBitsButton;
    private javax.swing.JButton buttonArangeByCustomBits;
    private javax.swing.JButton buttonAutoDetBits;
    private javax.swing.JButton buttonTopologyDrawCustomBitGroups;
    private javax.swing.JButton calcClustersButton;
    private javax.swing.JButton calcGroupOccButton;
    private javax.swing.JCheckBox checkExtStat;
    private javax.swing.JPanel clusterPanel;
    private javax.swing.JTextArea clustersText;
    private javax.swing.JPanel cogDiagramPanel;
    private javax.swing.JList configurationsList;
    private javax.swing.JPanel configurationsPanel;
    private javax.swing.JButton defArragementButton;
    private javax.swing.JRadioButton drawCurrentRadioButton;
    private javax.swing.JRadioButton drawMeanOccsRadioButton;
    private javax.swing.ButtonGroup drawTypeButtonGroup;
    private javax.swing.JTextArea groupOccText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel linkWeightingPanel;
    private javax.swing.JButton loadConfigButton;
    private javax.swing.JButton loadNetworkButton;
    private javax.swing.JPanel network1DPanel;
    private javax.swing.JPanel network2DPanel;
    private javax.swing.JPanel networkTopologyPanel;
    private javax.swing.JButton newConfigButton;
    private javax.swing.JButton overwriteConfigButton;
    private javax.swing.JButton recalcButton;
    private javax.swing.JButton removeConfigButton;
    private javax.swing.JButton reseedAndResetButton;
    private javax.swing.JButton reseedButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JToggleButton runButton;
    private javax.swing.JButton saveNetworkButton;
    private javax.swing.JButton setp_deadlyButton;
    private javax.swing.JSpinner spinnerLinkW0;
    private javax.swing.JSpinner spinnerLinkW1;
    private javax.swing.JSpinner spinnerLinkW10;
    private javax.swing.JSpinner spinnerLinkW11;
    private javax.swing.JSpinner spinnerLinkW2;
    private javax.swing.JSpinner spinnerLinkW3;
    private javax.swing.JSpinner spinnerLinkW4;
    private javax.swing.JSpinner spinnerLinkW5;
    private javax.swing.JSpinner spinnerLinkW6;
    private javax.swing.JSpinner spinnerLinkW7;
    private javax.swing.JSpinner spinnerLinkW8;
    private javax.swing.JSpinner spinnerLinkW9;
    private javax.swing.JSpinner spinnerMax_s;
    private javax.swing.JSpinner spinnerN;
    private javax.swing.JSpinner spinnerRedrawDelay;
    private javax.swing.JSpinner spinnerSeed;
    private javax.swing.JSpinner spinnerp;
    private javax.swing.JSpinner spinnerp_deadly;
    private javax.swing.JSpinner spinnert_l;
    private javax.swing.JSpinner spinnert_u;
    private javax.swing.JButton stepButton;
    private javax.swing.JLabel tLabel;
    private javax.swing.JTextField textCustomBitMask;
    private javax.swing.JTextField textCustomBitValues;
    private javax.swing.JRadioButton topologyDrawCurrentRadioButton;
    private javax.swing.JRadioButton topologyDrawMeansRadioButton;
    private javax.swing.ButtonGroup topologyDrawTypeButtonGroup;
    private javax.swing.JLabel totalOccLabel;
    // End of variables declaration//GEN-END:variables
}
